version: '3'

services:
  app:
    ## with build
#    build:
#      context: .
#      args:
#        APP_IMAGE: ${APP_IMAGE}
#        APP_TAG: ${APP_TAG}
#    image: ${APP_BUILD}:${APP_BUILD_TAG}
    ## with image only
    image: ${APP_IMAGE}:${APP_TAG}
    working_dir: /app
    container_name: ${COMPOSE_PROJECT_NAME}_app
    volumes:
      - ./app:/app:cached
      # php settings
      - ./conf/${PROVISION_CONTEXT}/php.ini:/usr/local/etc/php/conf.d/991-custom.ini
    ports:
      - ${EXTERNAL_HTTP_PORT}:80
      - ${EXTERNAL_HTTPS_PORT}:443
    environment:
      WEB_DOCUMENT_ROOT: ${WEB_DOCUMENT_ROOT}
      WEB_DOCUMENT_INDEX: ${WEB_DOCUMENT_INDEX}
      WEB_PHP_TIMEOUT: ${WEB_PHP_TIMEOUT}
      PHP_DEBUGGER: ${PHP_DEBUGGER}
      TYPO3_CONTEXT: ${PROVISION_CONTEXT}/Docker

  db:
    image: ${DB_IMAGE}:${DB_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_db
    volumes:
      - ./data/db/:/var/lib/mysql:delegated
    ports:
      - ${EXTERNAL_DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

#  cache:
#    image: ${CACHE_IMAGE}:${CACHE_TAG}
#    container_name: ${COMPOSE_PROJECT_NAME}_cache
#    volumes:
#      - ./data/cache:/data/:delegated
#    ports:
#      - ${EXTERNAL_CACHE_PORT}:6379
#    command: redis-server --appendonly yes

#  search:
#    image: ${SEARCH_IMAGE}:${SEARCH_TAG}
#    container_name: ${COMPOSE_PROJECT_NAME}_search
#    volumes:
#      - ./data/search:/opt/solr/server/solr/data/:delegated
#    ports:
#      - ${EXTERNAL_SEARCH_PORT}:8983

#  mail:
#    image: ${MAIL_IMAGE}:${MAIL_TAG}
#    container_name: ${COMPOSE_PROJECT_NAME}_mail
#    ports:
#      - ${EXTERNAL_MAIL_PORT}:8025

#  phpmyadmin:
#    image: ${DB_ADMIN_IMAGE}:${DB_ADMIN_TAG}
#    container_name: ${COMPOSE_PROJECT_NAME}_dbadmin
#    volumes:
#      - phpmyadmin:/sessions:delegated
#    ports:
#      - ${EXTERNAL_DB_ADMIN_PORT}:80
#    environment:
#      - PMA_HOST=db
#volumes:
#  phpmyadmin:
