version: '3.7'

volumes:
  processed:
  typo3temp:
  var:
  vendor:
  typo3:
  mysql:

services:
  app:
    image: ${APP_IMAGE}:${APP_TAG}
    working_dir: /app
    container_name: ${COMPOSE_PROJECT_NAME}_app
    volumes:
      - ./app:/app:cached
      # move directories to volumes
      - processed:/app/public/fileadmin/_processed_
      - typo3temp:/app/public/typo3temp
      - var:/app/var
      - vendor:/app/vendor
      - typo3:/app/public/typo3
      # mount composer cache
      - ~/.composer/cache:/home/application/.composer/cache
      # reenable cache mox_expire
      - ./conf/${PROVISION_CONTEXT}/02-dev.conf:/opt/docker/etc/httpd/vhost.common.d/02-dev.conf
      # add http2 settings
#      - ./conf/${PROVISION_CONTEXT}/http2.conf:/opt/docker/etc/httpd/vhost.common.d/03-http2.conf
      # add php settings
      - ./conf/${PROVISION_CONTEXT}/php.ini:/usr/local/etc/php/conf.d/991-custom.ini
      # add php xdebug profile paths
      - ./data/php-profiles/:/tmp/debug/:delegated
      # add ssh key for repository access
      #- ./conf/${PROVISION_CONTEXT}/ssh:/home/application/.ssh
      # replace ssl certs
      - ./conf/${PROVISION_CONTEXT}/ssl:/opt/docker/etc/httpd/ssl/
      # add crontab (run make crontab after rebuild)
      - ./conf/cron/crontab:/var/spool/cron/crontabs/application
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      WEB_DOCUMENT_ROOT: ${WEB_DOCUMENT_ROOT}
      WEB_DOCUMENT_INDEX: ${WEB_DOCUMENT_INDEX}
      WEB_PHP_TIMEOUT: ${WEB_PHP_TIMEOUT}
      PHP_DEBUGGER: ${PHP_DEBUGGER}
      PHP_DISMOD: ioncube,redis
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
      TYPO3_CONTEXT: ${PROVISION_CONTEXT}
#    command:
#      sh -c 'a2enmod http2 && supervisord'
    depends_on:
      - mysql

  node:
    image: ${NODE_IMAGE}:${NODE_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_node
    user: node
    working_dir: /app
    volumes:
      - ${NODE_SRC}:/app/src
      - ${NODE_DIST}:/app/dist

  mysql:
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    volumes:
      - mysql:/var/lib/mysql
#      - ./data/mysql/:/var/lib/mysql:delegated
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE}:${PHPMYADMIN_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  mailhog:
    image: ${MAILHOG_IMAGE}:${MAILHOG_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    ports:
      - ${MAILHOG_PORT}:8025
    depends_on:
      - app

