version: '3.7'

volumes:
  processed:
  typo3temp:
  var:
  vendor:
  typo3:
  ext:
  mysql:

services:
  app:
    image: ${APP_IMAGE}:${APP_TAG}
    working_dir: /app
    container_name: ${PROJECT_ID}_app
    volumes:
      - ./app:/app:cached
      # move directories to volumes
      - processed:/app/public/fileadmin/_processed_
      - typo3temp:/app/public/typo3temp
      - var:/app/var
      - vendor:/app/vendor
      - typo3:/app/public/typo3
      - ext:/app/public/typo3conf/ext
      # mount composer cache
      - ~/.composer/cache:/home/application/.composer/cache
      # reenable cache mox_expire
#      - ./conf/${PROVISION_CONTEXT}/02-dev.conf:/opt/docker/etc/httpd/vhost.common.d/02-dev.conf
      # add php xdebug profile paths
      - ./data/php-profiles/:/tmp/debug/:delegated
      # add ssh key for repository access
      - ./conf/ssh:/home/application/.ssh
      # replace ssl certs
      - ./conf/ssl:/opt/docker/etc/httpd/ssl/
      # add crontab (run make crontab after rebuild)
      - ./conf/cron/crontab:/var/spool/cron/crontabs/application
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      WEB_DOCUMENT_ROOT: ${WEB_DOCUMENT_ROOT}
      WEB_DOCUMENT_INDEX: ${WEB_DOCUMENT_INDEX}
      WEB_PHP_TIMEOUT: ${WEB_PHP_TIMEOUT}

      PHP_DEBUGGER: ${PHP_DEBUGGER}

      PHP_DISMOD: ioncube,redis
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE}
      PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS}
      XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
      XDEBUG_REMOTE_CONNECT_BACK: ${XDEBUG_REMOTE_CONNECT_BACK}
      XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}

      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}

      TYPO3_CONTEXT: ${PROVISION_CONTEXT}
    depends_on:
      - mysql

#  node:
#    image: ${NODE_IMAGE}:${NODE_TAG}
#    container_name: ${PROJECT_ID}_node
#    user: node
#    working_dir: /app
#    volumes:
#      - ${NODE_SRC}:/app/src
#      - ${NODE_DIST}:/app/dist

  mysql:
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    container_name: ${PROJECT_ID}_mysql
    volumes:
      - mysql:/var/lib/mysql
#      - ./data/mysql/:/var/lib/mysql:delegated
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE}:${PHPMYADMIN_TAG}
    container_name: ${PROJECT_ID}_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  mailhog:
    image: ${MAILHOG_IMAGE}:${MAILHOG_TAG}
    container_name: ${PROJECT_ID}_mailhog
    ports:
      - ${MAILHOG_PORT}:8025
    depends_on:
      - app

