version: '3'

services:
  app:
    image: ${APP_IMAGE}:${APP_TAG}
    working_dir: /app
    container_name: ${COMPOSE_PROJECT_NAME}_app
    volumes:
      - ./app:/app:cached
      # add php settings
      - ./conf/${PROVISION_CONTEXT}/php.ini:/usr/local/etc/php/conf.d/991-custom.ini
      # add crontab
      - ./conf/cron/crontab:/var/spool/cron/crontabs/application
      # add ssh key for repository access
      - ./conf/${PROVISION_CONTEXT}/ssh:/home/application/.ssh
      # replace ssl certs
      - ./conf/${PROVISION_CONTEXT}/ssl:/opt/docker/etc/httpd/ssl/
    ports:
      - ${EXTERNAL_HTTP_PORT}:80
      - ${EXTERNAL_HTTPS_PORT}:443
    environment:
      WEB_DOCUMENT_ROOT: ${WEB_DOCUMENT_ROOT}
      WEB_DOCUMENT_INDEX: ${WEB_DOCUMENT_INDEX}
      WEB_PHP_TIMEOUT: ${WEB_PHP_TIMEOUT}
      PHP_DEBUGGER: ${PHP_DEBUGGER}
      TYPO3_CONTEXT: ${PROVISION_CONTEXT}/Docker

  db:
    image: ${DB_IMAGE}:${DB_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_db
    volumes:
      - ./data/db/:/var/lib/mysql:delegated
    ports:
      - ${EXTERNAL_DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  dbadmin:
    image: ${DB_ADMIN_IMAGE}:${DB_ADMIN_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_dbadmin
    ports:
      - ${EXTERNAL_DB_ADMIN_PORT}:80
    environment:
      - PMA_HOST=db
