version: '3'

services:
  app:
    image: ${APP_IMAGE}:${APP_TAG}
    working_dir: /app
    container_name: ${COMPOSE_PROJECT_NAME}_app
    volumes:
      - ./app:/app:cached
      # mount composer cache
      - ~/.composer/cache:/home/application/.composer/cache
      # add php settings
      - ./conf/${PROVISION_CONTEXT}/php.ini:/usr/local/etc/php/conf.d/991-custom.ini
      # add php xdebug profile paths
      - ./data/php-profiles/:/tmp/debug/:delegated
      # add ssh key for repository access
      #- ./conf/${PROVISION_CONTEXT}/ssh:/home/application/.ssh
      # replace ssl certs
      #- ./conf/${PROVISION_CONTEXT}/ssl:/opt/docker/etc/httpd/ssl/
      # add crontab (run make crontab after rebuild)
      #- ./conf/cron/crontab:/var/spool/cron/crontabs/application
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      WEB_DOCUMENT_ROOT: ${WEB_DOCUMENT_ROOT}
      WEB_DOCUMENT_INDEX: ${WEB_DOCUMENT_INDEX}
      WEB_PHP_TIMEOUT: ${WEB_PHP_TIMEOUT}
      PHP_DEBUGGER: ${PHP_DEBUGGER}
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
      TYPO3_CONTEXT: ${PROVISION_CONTEXT}
    depends_on:
      - mysql

  mysql:
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    volumes:
      - ./data/mysql/:/var/lib/mysql:delegated
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE}:${PHPMYADMIN_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  mailhog:
    image: ${MAILHOG_IMAGE}:${MAILHOG_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    ports:
      - ${MAILHOG_PORT}:8025
    depends_on:
      - app
