version: '3'

services:

#######################################
# Redis
#######################################
  redis:
    build:
      context: redis
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    volumes:
      - ./../data/redis:/data/:delegated

# Memcached
#######################################
#memcached:
#  build:
#    context: docker/memcached/
#  container_name: ${COMPOSE_PROJECT_NAME}_memcached

