version: '3'

services:

  #######################################
  # Elasticsearch
  #######################################
  elasticsearch:
    build:
      context: elasticsearch
    ports:
      - 19200:9200
      - 19300:9300
    volumes:
      - ./../data/elasticsearch/:/usr/share/elasticsearch/data/:delegated


  #######################################
  # Solr server
  #######################################
#    solr:
#      build:
#        context: solr
#      container_name: ${COMPOSE_PROJECT_NAME}_solr
#      ports:
#        - 8983:8983
#      volumes:
#        - ./../data/solr:/opt/solr/server/solr/data/:delegated


  #######################################
  # Tika server
  #######################################
#    tika:
#      build:
#        context: tika
#      container_name: ${COMPOSE_PROJECT_NAME}_tika
#      ports:
#        - 9998:9998