version: '3'

services:
    app:
      links:
        - mail
        - mysql
#        - redis
#        - postgres
#        - elasticsearch
#        - solr
      environment:
        TYPO3_CONTEXT: ${PROVISION_CONTEXT}/Docker


  #######################################
  # MYSQL server
  #######################################
    mysql:
      build:
          context: mysql
          dockerfile: Dockerfile
          args:
            MYSQL_VERSION: ${MYSQL_VERSION}
      container_name: ${COMPOSE_PROJECT_NAME}_mysql
      environment:
          MYSQL_DATABASE: app_db
          MYSQL_USER: dev
          MYSQL_PASSWORD: dev
          MYSQL_ROOT_PASSWORD: dev
      ports:
        - ${EXTERNAL_DB_PORT}:3306
      volumes:
        - ./../data/mysql/:/var/lib/mysql:delegated


  #######################################
  # PostgreSQL server
  #######################################
#    postgres:
#      build:
#        context: postgres
#        dockerfile: Dockerfile
#      container_name: ${COMPOSE_PROJECT_NAME}_postgres
#      ports:
#        - 15432:5432
#      environment:
#        POSTGRES_DATABASE: app_db
#        POSTGRES_USER: dev
#        POSTGRES_PASSWORD: dev
#      volumes:
#        - ./../data/postgres/_db:/var/lib/postgresql/data/:delegated


  #######################################
  # mailhog
  #######################################
    mail:
       image: mailhog/mailhog
       ports:
         - ${EXTERNAL_MAIL_PORT}:8025
       container_name: ${COMPOSE_PROJECT_NAME}_mail
